# Group Members:
# Muhammad Mohsin Iqbal CS-19036
# Syed Mehdi Zafar CS-19027
# Hamza Junaid  CS-19037

# Imports

In [91]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
import pickle
from sklearn.svm import SVR
from sklearn.model_selection import train_test_split

# Preprocessing

In [92]:
# function for preprocessing
def preprocess():
    df=pd.read_csv("The_Grades_Dataset.csv") #read dataset into Dataframe
    target=df.CGPA  #separating CGPA column as target
    df.drop(["Seat No.","CGPA"],axis="columns",inplace=True) #dropping CGPA from input dataframe
    #encoding
    scale_mapper = {"A+":1, "A":2, "A-":3, "B+":4, "B":5, "B-":6, "C+":7, "C":8, "C-":9, "D+":10,"D":11,"F":12,"I":13,"W":14,"WU":15} 
    df=df.replace(scale_mapper) 
    df.fillna(8,inplace=True) #replace missing values with 8
    return df , target

# Linear Model

In [93]:
def Linear_model(df,target,num):
    df=df
    target=target
    num=num
    
    model=LinearRegression()  #calling LinearRegression 
    X = df.iloc[:, :].values
    X_train,X_test,Y_train,Y_test = train_test_split(X,target,test_size=0.2,random_state=0)
    model.fit(X_train,Y_train)#fitting inputs and target into the model
    #metrics
#     r_sq = model.score(X, target)
    train_score = model.score(X_train, Y_train)
    test_score = model.score(X_test, Y_test)
#     print(f"coefficient of determination of entire data: {r_sq}")
    print(f"coefficient of determination of training data using Linear Regression: {train_score}")
    print(f"coefficient of determination of test data using Linear Regression: {test_score}")
    print(f"intercept of the model: {model.intercept_}")
    print(f"slope of the model: {model.coef_}")
    pickle.dump(model,open( 'model'+num+'.pkl', 'wb'))  #dumping model in pickle file to save in harddisk from memory
    return model

# SVR Model

In [94]:
def svr_model(df,target,num):
    df=df
    X = df.iloc[:, :].values
    target=target
    num=num
    X_train,X_test,Y_train,Y_test = train_test_split(X,target,test_size=0.2,random_state=0)
    
    svr_rbf=SVR(C=1.0, epsilon=0.1, kernel='rbf')  #calling LinearRegression 
    svr_rbf.fit(X_train, Y_train)  #fitting inputs and target into the model
#     r_sq = svr_rbf.score(X, target)
    train_score = svr_rbf.score(X_train, Y_train)
    test_score = svr_rbf.score(X_test, Y_test)
#     print(f"coefficient of determination of entire data using SVR: {r_sq}")
    print(f"coefficient of determination of training data using SVR: {train_score}")
    print(f"coefficient of determination of test data using SVR: {test_score}")
   
    pickle.dump(svr_rbf,open( 'model_'+num+'.pkl', 'wb'))  #dumping model in pickle file to save in harddisk from memory  
    return svr_rbf

# Preparing dataframe for different models

In [95]:
def input_for_dataframe(df):
    x=input("Enter=> 1: First Year Courses 2: First Year and second year 3: First three years")
    if x=="3":
        #dropping 4th year courses from the dataset
        df.drop(["CS-403","MT-442","CS-421","CS-406","CS-414","CS-419","CS-423","CS-412"], axis="columns", inplace=True)
        return df, x
    if x=="2":
        #dropping 3rd and 4th year courses from the dataset
        df.drop(["CS-403","MT-442","CS-421","CS-406","CS-414","CS-419","CS-423","CS-412","MT-331","EF-303","HS-304","CS-301","CS-302","TC-383","EL-332","CS-318","CS-306","CS-312","CS-317"], axis="columns", inplace=True)
        return df, x
    if x=="1":
        #dropping 2nd,3rd and 4th year courses from the dataset
        df.drop(["CS-403","MT-442","CS-421","CS-406","CS-414","CS-419","CS-423","CS-412","MT-331","EF-303","HS-304","CS-301","CS-302","TC-383","EL-332","CS-318","CS-306","CS-312","CS-317","HS-205/20","MT-222","EE-222","MT-224","CS-210","CS-211","CS-203","CS-214","EE-217","CS-212","CS-215"], axis="columns", inplace=True)
        return df, x

# Main

In [96]:
#main 
df_preprocess=preprocess() #preprocessing the dataset
df=df_preprocess[0]        #saving dataframe in df variable
target=df_preprocess[1]    #saving target in target variable
df

,PH-121,HS-101,CY-105,HS-105/12,MT-111,CS-105,CS-106,EL-102,EE-119,ME-107,...,CS-306,CS-312,CS-317,CS-403,CS-421,CS-406,CS-414,CS-419,CS-423,CS-412
0,6,10,9.0,8.0,9.0,10,11.0,9.0,6.0,9.0,...,8.0,9.0,9.0,9.0,9.0,3.0,2.0,9.0,5.0,3.0
1,2,11,10.0,11.0,6.0,8,11.0,2.0,10.0,11.0,...,11.0,10.0,11.0,8.0,11.0,3.0,6.0,8.0,8.0,5.0
2,2,5,2.0,6.0,4.0,2,6.0,4.0,3.0,3.0,...,3.0,5.0,5.0,2.0,8.0,2.0,2.0,2.0,3.0,2.0
3,11,7,10.0,11.0,11.0,3,10.0,9.0,11.0,7.0,...,9.0,10.0,8.0,10.0,9.0,6.0,5.0,7.0,7.0,7.0
4,3,3,3.0,4.0,2.0,2,3.0,4.0,2.0,3.0,...,3.0,6.0,4.0,4.0,6.0,3.0,2.0,3.0,3.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
566,5,2,2.0,3.0,1.0,2,3.0,3.0,1.0,4.0,...,4.0,3.0,3.0,2.0,2.0,2.0,4.0,4.0,5.0,2.0
567,1,2,2.0,2.0,2.0,2,2.0,3.0,2.0,2.0,...,3.0,4.0,4.0,2.0,2.0,3.0,5.0,3.0,8.0,3.0
568,5,2,3.0,4.0,2.0,2,2.0,2.0,2.0,5.0,...,4.0,3.0,5.0,2.0,4.0,2.0,8.0,4.0,3.0,3.0
569,2,4,11.0,2.0,11.0,10,6.0,9.0,6.0,9.0,...,4.0,11.0,5.0,5.0,9.0,11.0,8.0,5.0,6.0,8.0
570,8,11,11.0,8.0,8.0,10,5.0,7.0,8.0,10.0,...,10.0,7.0,8.0,6.0,11.0,12.0,9.0,4.0,11.0,9.0

In [97]:
model_dataframe=input_for_dataframe(df) #input type of model from user 
df=model_dataframe[0]
x=model_dataframe[1]

Enter=> 1: First Year Courses 2: First Year and second year 3: First three years3

In [98]:
Linear=Linear_model(df,target,x)      #training with Linear Model

# #uncomment below line for prediction for first year
# # y_pred = Linear.predict([[1,5,1,5,3,1,3,6,2,6,8]])

# #uncomment below line for prediction for first two years
# # y_pred = Linear.predict([[1,5,1,5,3,1,3,6,2,6,8,1,5,1,5,3,1,3,6,2,6,8]])

# #uncomment below line for prediction for first three years
# # y_pred = Linear.predict([[1,5,1,5,3,1,3,6,2,6,8,1,5,1,5,3,1,3,6,2,6,8,8,1,5,1,5,3,1,3,6,2,6,8]])
# # print(f"Predicted CGPA:\n{y_pred}")
svr=svr_model(df,target,x)                 #training with svr model
# #uncomment below line for prediction for first year
# # y_pred2 = svr.predict([[1,5,1,5,3,1,3,6,2,6,8]])

# #uncomment below line for prediction for first two years
# # y_pred2 = svr.predict([[1,5,1,5,3,1,3,6,2,6,8,1,5,1,5,3,1,3,6,2,6,8]])

# #uncomment below line for prediction for first three years
# # y_pred2 = svr.predict([[1,5,1,5,3,1,3,6,2,6,8,1,5,1,5,3,1,3,6,2,6,8,8,1,5,1,5,3,1,3,6,2,6,8]])

# # print(f"Predicted CGPA:\n{y_pred}") 
# # print(f"Predicted CGPA:\n{y_pred2}")

coefficient of determination of training data using Linear Regression: 0.9711567480078183
coefficient of determination of test data using Linear Regression: 0.9844517160107494
intercept of the model: 4.604613855822261
slope of the model: [-0.00944285 -0.01388362 -0.00603933 -0.00179779 -0.01022087 -0.01791295
 -0.00623593 -0.00414383 -0.0231619  -0.01250252 -0.00450112 -0.01047541
 -0.00450072 -0.00649992 -0.01517853 -0.01372295 -0.00161887 -0.00376306
 -0.00169916 -0.01133056 -0.00271304 -0.00822599 -0.01226326 -0.00548898
 -0.0094446  -0.0207562  -0.01376745 -0.00757916 -0.01274628 -0.0035149
 -0.02026006 -0.01049837 -0.01213578]
coefficient of determination of training data using SVR: 0.9848965329999381
coefficient of determination of test data using SVR: 0.9712898148792424